strict: true

opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - closure_spacing
  - empty_count
  - sorted_imports
  - yoda_condition
  - explicit_init
  - redundant_nil_coalescing
  - first_where
  - last_where
  - contains_over_first_not_nil
  - empty_string
  - toggle_bool

identifier_name:
  min_length: 1

excluded:
  - .build
  - Derived
