strict: true

opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - vertical_whitespace_closing_braces
  - closure_spacing
  - empty_count
  - sorted_imports

disabled_rules:
  - trailing_comma

identifier_name:
  min_length: 1
  excluded:
    - id
    - to
    - a
    - b

excluded:
  - .build
  - Derived
  - "*.generated.swift"
